const List countriesList = [
  {"id": 96, "name": "India", "code": "IN"},
  {"id": 217, "name": "United Arab Emirates", "code": "AE"},
  {"id": 236, "name": "Saudi Arabia", "code": "SA"},
  {"id": 210, "name": "Qatar", "code": "QA"},
  {"id": 10, "name": "Bahrain", "code": "BH"},
  {"id": 193, "name": "Oman", "code": "OM"},
  {"id": 220, "name": "Yemen", "code": "YE"},
  {"id": 130, "name": "Kuwait", "code": "KW"},
  {"id": 71, "name": "Egypt", "code": "EG"},
  {"id": 218, "name": "United States", "code": "US"},
  {"id": 32, "name": "France", "code": "FR"},
  {"id": 1, "name": "Argentina", "code": "AR"},
  {"id": 2, "name": "Antigua and Barbuda", "code": "AG"},
  {"id": 3, "name": "Aland Islands", "code": "AX"},
  {"id": 4, "name": "Armenia", "code": "AM"},
  {"id": 5, "name": "Aruba", "code": "AW"},
  {"id": 6, "name": "Afghanistan", "code": "AF"},
  {"id": 7, "name": "Australia", "code": "AU"},
  {"id": 8, "name": "Austria", "code": "AT"},
  {"id": 9, "name": "Azerbaijan", "code": "AZ"},
  {"id": 11, "name": "Anguilla", "code": "AI"},
  {"id": 12, "name": "Belarus", "code": "BY"},
  {"id": 13, "name": "Bangladesh", "code": "BD"},
  {"id": 14, "name": "Antarctica", "code": "AQ"},
  {"id": 15, "name": "Belgium", "code": "BE"},
  {"id": 16, "name": "Barbados", "code": "BB"},
  {"id": 17, "name": "Belize", "code": "BZ"},
  {"id": 18, "name": "Benin", "code": "BJ"},
  {"id": 19, "name": "Bermuda", "code": "BM"},
  {"id": 20, "name": "Bhutan", "code": "BT"},
  {"id": 21, "name": "Bolivia", "code": "BO"},
  {"id": 22, "name": "Bosnia and Herzegovina", "code": "BA"},
  {"id": 23, "name": "Bouvet Island", "code": "BV"},
  {"id": 24, "name": "Eswatini", "code": "SZ"},
  {"id": 25, "name": "Ethiopia", "code": "ET"},
  {"id": 26, "name": "Falkland Islands", "code": "FK"},
  {"id": 27, "name": "Faroe Islands", "code": "FO"},
  {"id": 28, "name": "Finland", "code": "FI"},
  {"id": 29, "name": "Fiji Islands", "code": "FJ"},
  {"id": 30, "name": "French Polynesia", "code": "PF"},
  {"id": 31, "name": "French Guiana", "code": "GF"},
  {"id": 33, "name": "Bonaire", "code": "BQ"},
  {"id": 34, "name": "Botswana", "code": "BW"},
  {"id": 35, "name": "Angola", "code": "AO"},
  {"id": 36, "name": "British Indian Ocean T", "code": "IO"},
  {"id": 37, "name": "Brazil", "code": "BR"},
  {"id": 38, "name": "Brunei", "code": "BN"},
  {"id": 39, "name": "Bulgaria", "code": "BG"},
  {"id": 40, "name": "Burundi", "code": "BI"},
  {"id": 41, "name": "Burkina Faso", "code": "BF"},
  {"id": 42, "name": "Cameroon", "code": "CM"},
  {"id": 43, "name": "Cayman Islands", "code": "KY"},
  {"id": 44, "name": "Canada", "code": "CA"},
  {"id": 45, "name": "Cape Verde", "code": "CV"},
  {"id": 46, "name": "Central African Republic", "code": "CF"},
  {"id": 47, "name": "Chad", "code": "TD"},
  {"id": 48, "name": "Cambodia", "code": "KH"},
  {"id": 49, "name": "Chile", "code": "CL"},
  {"id": 50, "name": "China", "code": "CN"},
  {"id": 51, "name": "Cocos (Keeling) Islands", "code": "CC"},
  {"id": 52, "name": "Christmas Island", "code": "CX"},
  {"id": 53, "name": "Colombia", "code": "CO"},
  {"id": 54, "name": "Comoros", "code": "KM"},
  {"id": 55, "name": "Cook Islands", "code": "CK"},
  {"id": 56, "name": "Congo", "code": "CG"},
  {"id": 57, "name": "Costa Rica", "code": "CR"},
  {"id": 58, "name": "Croatia", "code": "HR"},
  {"id": 59, "name": "Cuba", "code": "CU"},
  {"id": 60, "name": "Curaçao", "code": "CW"},
  {"id": 61, "name": "Czech Republic", "code": "CZ"},
  {"id": 62, "name": "Cyprus", "code": "CY"},
  {"id": 63, "name": "DR Congo", "code": "CD"},
  {"id": 64, "name": "Denmark", "code": "DK"},
  {"id": 65, "name": "Djibouti", "code": "DJ"},
  {"id": 66, "name": "Dominica", "code": "DM"},
  {"id": 67, "name": "Ecuador", "code": "EC"},
  {"id": 68, "name": "Dominican Republic", "code": "DO"},
  {"id": 69, "name": "El Salvador", "code": "SV"},
  {"id": 70, "name": "Equatorial Guinea", "code": "GQ"},
  {"id": 72, "name": "Eritrea", "code": "ER"},
  {"id": 73, "name": "French Southern Territories", "code": "TF"},
  {"id": 74, "name": "Gabon", "code": "GA"},
  {"id": 75, "name": "Estonia", "code": "EE"},
  {"id": 76, "name": "Gibraltar", "code": "GI"},
  {"id": 77, "name": "Georgia", "code": "GE"},
  {"id": 78, "name": "Ghana", "code": "GH"},
  {"id": 79, "name": "Greece", "code": "GR"},
  {"id": 80, "name": "Germany", "code": "DE"},
  {"id": 81, "name": "Greenland", "code": "GL"},
  {"id": 82, "name": "Guadeloupe", "code": "GP"},
  {"id": 83, "name": "Grenada", "code": "GD"},
  {"id": 84, "name": "Guam", "code": "GU"},
  {"id": 85, "name": "Guatemala", "code": "GT"},
  {"id": 86, "name": "Guernsey", "code": "GG"},
  {"id": 87, "name": "Guinea", "code": "GN"},
  {"id": 88, "name": "Guinea-Bissau", "code": "GW"},
  {"id": 89, "name": "Heard Island", "code": "HM"},
  {"id": 90, "name": "Hungary", "code": "HU"},
  {"id": 91, "name": "Haiti", "code": "HT"},
  {"id": 92, "name": "Guyana", "code": "GY"},
  {"id": 93, "name": "Honduras", "code": "HN"},
  {"id": 94, "name": "Iceland", "code": "IS"},
  {"id": 95, "name": "Hong Kong S.A.R.", "code": "HK"},
  {"id": 97, "name": "Indonesia", "code": "ID"},
  {"id": 98, "name": "Iran", "code": "IR"},
  {"id": 99, "name": "Iraq", "code": "IQ"},
  {"id": 100, "name": "Ireland", "code": "IE"},
  {"id": 101, "name": "Netherlands", "code": "NL"},
  {"id": 102, "name": "New Caledonia", "code": "NC"},
  {"id": 103, "name": "New Zealand", "code": "NZ"},
  {"id": 104, "name": "Nicaragua", "code": "NI"},
  {"id": 105, "name": "North Macedonia", "code": "MK"},
  {"id": 106, "name": "Niger", "code": "NE"},
  {"id": 107, "name": "Nigeria", "code": "NG"},
  {"id": 108, "name": "Northern Mariana", "code": "MP"},
  {"id": 109, "name": "Niue", "code": "NU"},
  {"id": 110, "name": "Norfolk Island", "code": "NF"},
  {"id": 111, "name": "North Korea", "code": "KP"},
  {"id": 112, "name": "South Georgia", "code": "GS"},
  {"id": 113, "name": "South Africa", "code": "ZA"},
  {"id": 114, "name": "Albania", "code": "AL"},
  {"id": 115, "name": "American Samoa", "code": "AS"},
  {"id": 116, "name": "Algeria", "code": "DZ"},
  {"id": 117, "name": "Andorra", "code": "AD"},
  {"id": 118, "name": "Israel", "code": "IL"},
  {"id": 119, "name": "Italy", "code": "IT"},
  {"id": 120, "name": "Ivory Coast", "code": "CI"},
  {"id": 121, "name": "South Korea", "code": "KR"},
  {"id": 122, "name": "Jamaica", "code": "JM"},
  {"id": 123, "name": "Japan", "code": "JP"},
  {"id": 124, "name": "Jersey", "code": "JE"},
  {"id": 125, "name": "Jordan", "code": "JO"},
  {"id": 126, "name": "Kosovo", "code": "XK"},
  {"id": 127, "name": "Kazakhstan", "code": "KZ"},
  {"id": 128, "name": "Kenya", "code": "KE"},
  {"id": 129, "name": "Kiribati", "code": "KI"},
  {"id": 131, "name": "Latvia", "code": "LV"},
  {"id": 132, "name": "Kyrgyzstan", "code": "KG"},
  {"id": 133, "name": "Lebanon", "code": "LB"},
  {"id": 134, "name": "Laos", "code": "LA"},
  {"id": 135, "name": "Spain", "code": "ES"},
  {"id": 136, "name": "South Sudan", "code": "SS"},
  {"id": 137, "name": "Sri Lanka", "code": "LK"},
  {"id": 138, "name": "Sudan", "code": "SD"},
  {"id": 139, "name": "Libya", "code": "LY"},
  {"id": 140, "name": "Lesotho", "code": "LS"},
  {"id": 141, "name": "Liechtenstein", "code": "LI"},
  {"id": 142, "name": "Liberia", "code": "LR"},
  {"id": 143, "name": "Macau S.A.R.", "code": "MO"},
  {"id": 144, "name": "Suriname", "code": "SR"},
  {"id": 145, "name": "Lithuania", "code": "LT"},
  {"id": 146, "name": "Luxembourg", "code": "LU"},
  {"id": 147, "name": "Malaysia", "code": "MY"},
  {"id": 148, "name": "Madagascar", "code": "MG"},
  {"id": 149, "name": "Svalbard Islands", "code": "SJ"},
  {"id": 150, "name": "Mali", "code": "ML"},
  {"id": 151, "name": "Maldives", "code": "MV"},
  {"id": 152, "name": "Malawi", "code": "MW"},
  {"id": 153, "name": "Malta", "code": "MT"},
  {"id": 154, "name": "Syria", "code": "SY"},
  {"id": 155, "name": "Sweden", "code": "SE"},
  {"id": 156, "name": "Man (Isle of)", "code": "IM"},
  {"id": 157, "name": "Marshall Islands", "code": "MH"},
  {"id": 158, "name": "Martinique", "code": "MQ"},
  {"id": 159, "name": "Mauritius", "code": "MU"},
  {"id": 160, "name": "Mauritania", "code": "MR"},
  {"id": 161, "name": "Mayotte", "code": "YT"},
  {"id": 162, "name": "Switzerland", "code": "CH"},
  {"id": 163, "name": "Micronesia", "code": "FM"},
  {"id": 164, "name": "Taiwan", "code": "TW"},
  {"id": 165, "name": "Mexico", "code": "MX"},
  {"id": 166, "name": "Moldova", "code": "MD"},
  {"id": 167, "name": "Monaco", "code": "MC"},
  {"id": 168, "name": "Mongolia", "code": "MN"},
  {"id": 169, "name": "Montenegro", "code": "ME"},
  {"id": 170, "name": "Tajikistan", "code": "TJ"},
  {"id": 171, "name": "Montserrat", "code": "MS"},
  {"id": 172, "name": "Tanzania", "code": "TZ"},
  {"id": 173, "name": "Thailand", "code": "TH"},
  {"id": 174, "name": "The Bahamas", "code": "BS"},
  {"id": 175, "name": "Morocco", "code": "MA"},
  {"id": 176, "name": "Namibia", "code": "NA"},
  {"id": 177, "name": "Mozambique", "code": "MZ"},
  {"id": 178, "name": "Nauru", "code": "NR"},
  {"id": 179, "name": "Myanmar", "code": "MM"},
  {"id": 180, "name": "Nepal", "code": "NP"},
  {"id": 181, "name": "The Gambia", "code": "GM"},
  {"id": 182, "name": "Norway", "code": "NO"},
  {"id": 183, "name": "Timor-Leste", "code": "TL"},
  {"id": 184, "name": "Togo", "code": "TG"},
  {"id": 185, "name": "Tokelau", "code": "TK"},
  {"id": 186, "name": "Tonga", "code": "TO"},
  {"id": 187, "name": "Turkey", "code": "TR"},
  {"id": 188, "name": "Trinidad and Tobago", "code": "TT"},
  {"id": 189, "name": "Tunisia", "code": "TN"},
  {"id": 190, "name": "US Minor Outlying Islands", "code": "UM"},
  {"id": 191, "name": "Uruguay", "code": "UY"},
  {"id": 192, "name": "Palestine", "code": "PS"},
  {"id": 194, "name": "Pakistan", "code": "PK"},
  {"id": 195, "name": "Papua New Guinea", "code": "PG"},
  {"id": 196, "name": "Panama", "code": "PA"},
  {"id": 197, "name": "Paraguay", "code": "PY"},
  {"id": 198, "name": "Peru", "code": "PE"},
  {"id": 199, "name": "Philippines", "code": "PH"},
  {"id": 200, "name": "Poland", "code": "PL"},
  {"id": 201, "name": "Pitcairn Island", "code": "PN"},
  {"id": 202, "name": "Uzbekistan", "code": "UZ"},
  {"id": 203, "name": "Turkmenistan", "code": "TM"},
  {"id": 204, "name": "Vanuatu", "code": "VU"},
  {"id": 205, "name": "Puerto Rico", "code": "PR"},
  {"id": 206, "name": "Portugal", "code": "PT"},
  {"id": 207, "name": "Turks and Caicos Islands", "code": "TC"},
  {"id": 208, "name": "Palau", "code": "PW"},
  {"id": 209, "name": "Vatican City", "code": "VA"},
  {"id": 211, "name": "Venezuela", "code": "VE"},
  {"id": 212, "name": "Vietnam", "code": "VN"},
  {"id": 213, "name": "Tuvalu", "code": "TV"},
  {"id": 214, "name": "Reunion", "code": "RE"},
  {"id": 215, "name": "Uganda", "code": "UG"},
  {"id": 216, "name": "Ukraine", "code": "UA"},
  {"id": 219, "name": "Romania", "code": "RO"},
  {"id": 221, "name": "United Kingdom", "code": "GB"},
  {"id": 222, "name": "Rwanda", "code": "RW"},
  {"id": 223, "name": "Russia", "code": "RU"},
  {"id": 224, "name": "Virgin Islands (US)", "code": "VI"},
  {"id": 225, "name": "Wallis and Futuna Islands", "code": "WF"},
  {"id": 226, "name": "Western Sahara", "code": "EH"},
  {"id": 227, "name": "Virgin Islands (British)", "code": "VG"},
  {"id": 228, "name": "Saint Kitts and Nevis", "code": "KN"},
  {"id": 229, "name": "Zambia", "code": "ZM"},
  {"id": 230, "name": "Zimbabwe", "code": "ZW"},
  {"id": 231, "name": "Saint Helena", "code": "SH"},
  {"id": 232, "name": "Saint Lucia", "code": "LC"},
  {"id": 233, "name": "Saint Vincent", "code": "VC"},
  {"id": 234, "name": "Saint-Barthelemy", "code": "BL"},
  {"id": 235, "name": "Saint Pierre and Miquelon", "code": "PM"},
  {"id": 237, "name": "Senegal", "code": "SN"},
  {"id": 238, "name": "Serbia", "code": "RS"},
  {"id": 239, "name": "Sierra Leone", "code": "SL"},
  {"id": 240, "name": "Samoa", "code": "WS"},
  {"id": 241, "name": "San Marino", "code": "SM"},
  {"id": 242, "name": "Singapore", "code": "SG"},
  {"id": 243, "name": "Seychelles", "code": "SC"},
  {"id": 244, "name": "Sint Maarten (Dutch part)", "code": "SX"},
  {"id": 245, "name": "Slovakia", "code": "SK"},
  {"id": 246, "name": "Sao Tome and Principe", "code": "ST"},
  {"id": 247, "name": "Slovenia", "code": "SI"},
  {"id": 248, "name": "Solomon Islands", "code": "SB"},
  {"id": 249, "name": "Somalia", "code": "SO"},
  {"id": 250, "name": "Saint-Martin ", "code": "MF"},
];

int getCountryIdByCode(String code) {
  final country = countriesList.firstWhere((c) => c['code'] == code);
  return country['id'];
}
